version: "3.9"

services:
  frontend:
    build: .
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    # env_file:
    #   - .env.development
    environment:
      - VITE_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    command: npm run dev -- --host
